services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    expose:
      - "3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    restart: on-failure
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    expose:
      - "9000"
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    restart: on-failure
    networks:
      - inception
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    restart: on-failure
    networks:
      - inception
    depends_on:
      - wordpress

volumes:
  mariadb_data:
  wordpress_data:

networks:
  inception:
