services:
  mariadb:
    container_name: mariadb
    build: ./mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    restart: on-failure
    networks:
      - inception
  wordpress:
    container_name: wordpress
    build: ./wordpress
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    restart: on-failure
    networks:
      - inception
    depends_on:
      - mariadb

volumes:
  mariadb_data:
  wordpress_data:

networks:
  inception:
