# Docker Compose is a tool for defining and running multi-container Docker applications.
# In this file, we define the services that will be used: mariadb, wordpress and nginx.

# Services are the building blocks of a Docker Compose application.
services:

  mariadb:
    container_name: mariadb                  # Name of the container
    build: ./requirements/mariadb            # Path to the Dockerfile
    expose:                                  # Expose ports without publishing them to the host machine
      - "3306"
    volumes:                                 # Mount the volume to the container
      - mariadb_data:/var/lib/mysql
    env_file:                                # Load environment variables from a file
      - .env
    restart: on-failure                      # Restart the container if it fails
    networks:                                # Connect the container to the network
      - inception

  wordpress:
    container_name: wordpress                # Name of the container
    build: ./requirements/wordpress          # Path to the Dockerfile
    expose:                                  # Expose ports without publishing them to the host machine
      - "9000"
    volumes:                                 # Mount the volume to the container
      - wordpress_data:/var/www/wordpress
    env_file:                                # Load environment variables from a file
      - .env
    restart: on-failure                      # Restart the container if it fails
    networks:                                # Connect the container to the network
      - inception
    depends_on:                              # Wait for the mariadb container to be ready before starting
      - mariadb

  nginx:
    container_name: nginx                    # Name of the container
    build: ./requirements/nginx              # Path to the Dockerfile
    ports:                                   # Publish the ports to the host machine
      - "443:443"
    volumes:
      - wordpress_data:/var/www/wordpress
    env_file:                                # Load environment variables from a file
      - .env
    restart: on-failure                      # Restart the container if it fails
    networks:                                # Connect the container to the network
      - inception
    depends_on:                              # Wait for the wordpress container to be ready before starting
      - wordpress

# Volumes are used to persist data generated by and used by Docker containers.
volumes:

  mariadb_data:
    driver: local                            # Use the local driver to create a volume
    driver_opts:                             # Define the options for the driver
      type: none                             # Type of the volume (none, tmpfs, local, etc.)
      device: /home/ataboada/data/mariadb    # Path to the volume
      o: bind                                # Bind the volume to the path

  wordpress_data:
    driver: local                           # Use the local driver to create a volume
    driver_opts:                            # Define the options for the driver
      type: none                            # Type of the volume (none, tmpfs, local, etc.)
      device: /home/ataboada/data/wordpress # Path to the volume
      o: bind                               # Bind the volume to the path

# Networks are used to connect Docker containers to each other.
networks:
  inception:
    driver: bridge                          # We use the bridge driver to create a network - the default driver
